name: libwebp manual compile for the Windows platform
# Unicode should be on by default with CMake

# Dispatch event:
# curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Ruzgfpegk/libwebp/actions/workflows/1/dispatches

on:
  workflow_dispatch:
  push:
    tags:
    - v1.1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: gcc
        cxx: g++
        build-type: Release
        # Extra options pass to cmake while configuring project
        configure-options: -DWEBP_BUILD_CWEBP=ON -DWEBP_UNICODE=ON
        # install the build using cmake --install
        install-build: true
        # run build using '-j [parallel]' to use multiple threads to build
        parallel: 14
